name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24.0.5-dind
        options: --privileged

    env:
      DOCKER_TLS_CERTDIR: "/certs"

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Clone frappe_docker Repository
      run: |
        git clone https://github.com/frappe/frappe_docker

    - name: Build and Push Docker Image
      run: |
        source ./build.env
        echo "REGISTRY=${REGISTRY}"
        echo "PROJECT_NAME=${PROJECT_NAME}"
        export APPS_JSON_BASE64=$(base64 -w 0 ./apps.json)
        echo "${APPS_JSON_BASE64}"
        export IMAGE_NAME=${REGISTRY}/${PROJECT_NAMESPACE}/${PROJECT_NAME}/${IMAGE}:$(cat ./version.txt)
        echo "Building Docker image: ${IMAGE_NAME}"
        cd frappe_docker
        docker build \
          --build-arg=FRAPPE_PATH=${FRAPPE_REPO} \
          --build-arg=FRAPPE_BRANCH=${FRAPPE_VERSION} \
          --build-arg=PYTHON_VERSION=${PY_VERSION} \
          --build-arg=NODE_VERSION=${NODEJS_VERSION} \
          --build-arg=APPS_JSON_BASE64=${APPS_JSON_BASE64} \
          --tag=${IMAGE_NAME} \
          --file=${DOCKERFILE} .
        docker push ${IMAGE_NAME}
