name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Docker
      run: |
        brew install --cask docker

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Clone frappe_docker Repository
      run: |
        git clone https://github.com/frappe/frappe_docker

    - name: Build and Push Docker Image
      run: |
        source ./build.env
        export APPS_JSON_BASE64=$(base64 -w 0 ./apps.json)
        export IMAGE_NAME=${REGISTRY}/${PROJECT_NAMESPACE}/${PROJECT_NAME}/${IMAGE}:$(cat ./version.txt)
        cd frappe_docker
        docker build \
          --build-arg=FRAPPE_PATH=${FRAPPE_REPO} \
          --build-arg=FRAPPE_BRANCH=${FRAPPE_VERSION} \
          --build-arg=PYTHON_VERSION=${PY_VERSION} \
          --build-arg=NODE_VERSION=${NODEJS_VERSION} \
          --build-arg=APPS_JSON_BASE64=${APPS_JSON_BASE64} \
          --tag=${IMAGE_NAME} \
          --file=${DOCKERFILE} .
        docker push ${IMAGE_NAME}
